version: "3"
services:
  database:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=paracetamal"
    ports:
      - 5432:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
